### ISSUE TITLE
You should deploy it on github pages. 

### ISSUE THREAD

**Issue by abhie16** [soham0w0sarkar/piano#1]

**Comment by soham0w0sarkar** [comment]
Idk what you mean!?

**Comment by abhie16** [comment]
![image](https://user-images.githubusercontent.com/95357648/192347949-3f3f32e5-cfb2-4115-991f-8d7b382db6af.png)


Follow the sequence of numbers. It will host your static site

**Comment by soham0w0sarkar** [comment]
damn bro!! thankyou for info and effort
